[package]
name = "Basic-FTP-Client-Server"
version = "0.1.0"
authors = ["Erick Elizondo <erick.elizondo20@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
